# Generated by Django 3.2 on 2021-06-05 12:02

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(db_index=True, max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(db_index=True, max_length=150, verbose_name='last name')),
                ('father_s_name', models.CharField(db_index=True, max_length=50, verbose_name='fathers name')),
                ('gender', models.CharField(choices=[('f', 'زن'), ('m', 'مزد')], max_length=1, null=True, verbose_name='جنسیت')),
                ('birth_certificate_id', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='birth certificate id')),
                ('national_code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='national code')),
                ('birthday', models.DateField(null=True, verbose_name='تاریخ تولد')),
                ('issueplace', models.CharField(max_length=50, verbose_name='issue place')),
                ('degree', models.CharField(choices=[('elementary ', 'ابتدایی'), ('middle-school', 'سیکل'), ('diploma', 'دیپلم'), ('associate', 'فوق دیپلم'), ('bachelor', 'لیسانس'), ('master', 'فوق لیسانس'), ('phd', 'دکترا'), ('post-doctoral', 'فوق دکترا')], max_length=13, null=True, verbose_name='مقطع تحصیلی')),
                ('major', models.CharField(max_length=255, null=True, verbose_name='رشته تحصیلی')),
                ('university_of_study', models.CharField(max_length=255, null=True, verbose_name='دانشگاه محل تحصیل')),
                ('executive_device', models.CharField(max_length=255, null=True, verbose_name='دستگاه اجرایی')),
                ('role', models.CharField(db_index=True, max_length=50, null=True, verbose_name='سمت')),
                ('work_experience', models.TextField(null=True, verbose_name='سابقه کاری')),
                ('personnel_id', models.CharField(db_index=True, max_length=50, null=True, verbose_name='شماره پرسنلی')),
                ('address', models.TextField(null=True, verbose_name='آدرس')),
                ('zip_code', models.CharField(max_length=10, null=True, verbose_name='کدپستی')),
                ('mobile', models.CharField(db_index=True, max_length=11, null=True, verbose_name='شماره موبایل')),
                ('necessary_contact_number', models.CharField(max_length=11, null=True, verbose_name='شماره تماس ضروری')),
                ('workplace_number', models.CharField(max_length=11, null=True, verbose_name='شماره محل کار')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='ایمیل')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='نام کاربری')),
                ('profile', models.ImageField(default='static/images/default/default-profile.jpg', upload_to='media/images/user/profile/', verbose_name='پروفایل')),
                ('access_group', models.CharField(blank=True, choices=[('user', 'کاربر'), ('department_of_administration', 'ریاست اداره'), ('deputy_for_planning_and_civil_affairs', 'معاونت امور برنامه ریزی و عمرانی'), ('governor', 'فرماندار')], max_length=37, null=True, verbose_name='گروه دسترسی')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/images/user/picture/', verbose_name='عکس')),
                ('personal_id_card', models.ImageField(blank=True, null=True, upload_to='media/images/user/personal_id_card/', verbose_name='کارت شناسایی پرسنلی')),
                ('device_introduction_letter', models.FileField(blank=True, null=True, upload_to='media/files/user/device_introduction_letter/', verbose_name='معرفی نامه دستگاه')),
                ('sample_signature', models.ImageField(blank=True, null=True, upload_to='media/images/user/signature/', verbose_name='نمونه امضا')),
                ('superuser', models.BooleanField(default=False, verbose_name='وضعیت مدیریت')),
                ('staff', models.BooleanField(default=False, verbose_name='وضعیت کارمند')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('history', models.JSONField(default=main.models.default_history_field(), verbose_name='تاریخچه')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت کاربر')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی کاربر')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ('id', 'create_date'),
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('validation_code', models.CharField(default=main.models.create_validation_code(6), max_length=6, verbose_name='کد فعال سازی')),
                ('createdatetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
            ],
        ),
    ]
