# Generated by Django 3.2 on 2021-06-12 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210606_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('fiscal_year', models.CharField(max_length=4, verbose_name='سال مالی')),
                ('executive_device', models.CharField(max_length=255, null=True, verbose_name='دستگاه اجرایی')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='media/files/project/', verbose_name='فایل پیوست')),
                ('project_location_address', models.TextField(verbose_name='آدرس محل پروژه')),
                ('telephone', models.CharField(max_length=8, verbose_name='شماره تماس')),
                ('approximate_date_preparation', models.DateField(verbose_name='تاریخ تقریبی بهره برداری')),
                ('amount_required_for_workshop', models.CharField(max_length=15, verbose_name='مبلغ مورد نیاز برای تجهیز کارگاه')),
                ('prepayment_amount', models.CharField(max_length=15, verbose_name='مبلغ پیش پرداخت')),
                ('initial_offered_credit_amount', models.CharField(max_length=15, verbose_name='مبلغ اعتبار پیشنهاد اولیه')),
                ('amount_credit_increase', models.CharField(max_length=15, verbose_name='میزان مبلغ افزایش اعتبار')),
                ('bidding_history', models.BooleanField(default=False, verbose_name='سابقه انجام مناقصه')),
                ('land_and_basic_facilities', models.BooleanField(default=False, verbose_name='زمین و امکانات اولیه')),
                ('similar_projects', models.JSONField(default=main.models.default_similar_projects_field(), verbose_name='پروژه های مشابه')),
                ('ability_to_shred', models.BooleanField(default=False, verbose_name='قابلیت کوچک شدن')),
                ('type_of_financial_resources', models.TextField(blank=True, null=True, verbose_name='نوع منابع مالی')),
                ('applicant_name_and_role', models.CharField(max_length=255, verbose_name='نام درخواست کننده / سمت')),
                ('requires_collaboration_between_devices', models.JSONField(default=main.models.default_requires_field(), verbose_name='نیاز به همکاری بین دستگاه')),
                ('requires_special_permissions', models.JSONField(default=main.models.default_requires_field(), verbose_name='نیاز مجوز خاص')),
                ('requires_special_facilities', models.JSONField(default=main.models.default_requires_field(), verbose_name='نیاز امکانات خاص')),
                ('shared_capability_between_multiple_executive_devices', models.JSONField(default=main.models.default_requires_field(), verbose_name='قابلیت اشتراکی بین چند دستگاه اجرایی')),
                ('shared_capability_between_several_cities', models.JSONField(default=main.models.default_requires_field(), verbose_name='قابلیت اشتراکی بین چند شهرستان')),
                ('history', models.JSONField(blank=True, null=True, verbose_name='تاریخچه')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
                'ordering': ('id', 'create_date'),
            },
        ),
    ]
