# Generated by Django 3.2 on 2021-06-13 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210613_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(choices=[('elementary', 'ابتدایی'), ('middle-school', 'سیکل'), ('diploma', 'دیپلم'), ('associate', 'فوق دیپلم'), ('bachelor', 'لیسانس'), ('master', 'فوق لیسانس'), ('phd', 'دکترا'), ('post-doctoral', 'فوق دکترا')], max_length=13, null=True, verbose_name='مقطع تحصیلی'),
        ),
        migrations.CreateModel(
            name='Official_Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='media/files/official_letter/', verbose_name='فایل پیوست')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'خوانده نشده'), (1, 'خوانده شده'), (2, 'پاسخ داده شده'), (3, 'دیدن پاسخ')], default=0, verbose_name='وضعیت نامه')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('fk_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_letter_receiver', to=settings.AUTH_USER_MODEL, verbose_name='کاربر دریافت کننده')),
                ('fk_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_letter_sender', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ارسال کننده')),
            ],
            options={
                'verbose_name': 'مکاتبه',
                'verbose_name_plural': 'مکاتبات',
                'ordering': ('id', 'create_date'),
            },
        ),
    ]
