# Generated by Django 3.2 on 2021-06-13 16:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210613_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='شرح')),
                ('score', models.CharField(max_length=4, verbose_name='امتیاز')),
                ('history', models.JSONField(default=main.models.default_history_field(), verbose_name='تاریخچه')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع پروژه',
                'verbose_name_plural': 'انواع پروژه ها',
                'ordering': ('id', 'create_date'),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(choices=[('elementary', 'ابتدایی'), ('middle-school', 'سیکل'), ('diploma', 'دیپلم'), ('associate', 'فوق دیپلم'), ('bachelor', 'لیسانس'), ('master', 'فوق لیسانس'), ('phd', 'دکترا'), ('post-doctoral', 'فوق دکترا')], max_length=13, null=True, verbose_name='مقطع تحصیلی'),
        ),
    ]
