# Generated by Django 3.2 on 2021-06-13 16:08

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210613_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='official_letter',
            name='answer',
            field=models.JSONField(default=main.models.default_answer_field(), verbose_name='پاسخ نامه'),
        ),
    ]
