# Generated by Django 3.2 on 2021-06-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210613_2040'),
        ('main', '0006_official_letter_answer'),
    ]

    operations = [
    ]
