# Generated by Django 3.2 on 2021-06-14 13:48

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20210613_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='evaluation_assistance',
            field=models.JSONField(blank=True, null=True, verbose_name='ارزیابی مدیریت برنامه ریزی و عمرانی'),
        ),
        migrations.AddField(
            model_name='project',
            name='evaluation_governor',
            field=models.JSONField(blank=True, null=True, verbose_name='ارزیابی فرماندار'),
        ),
        migrations.AddField(
            model_name='project',
            name='evaluation_point',
            field=models.PositiveIntegerField(default=0, verbose_name='مجموع امتیاز ارزیابی'),
        ),
        migrations.AddField(
            model_name='project',
            name='evaluation_user',
            field=models.JSONField(default=main.models.default_evaluation_user_field(), verbose_name='ارزیابی کاربر'),
        ),
    ]
