# Generated by Django 3.2 on 2021-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_executive_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='evaluation_governor',
        ),
        migrations.AddField(
            model_name='executive_device',
            name='evaluation_governor',
            field=models.IntegerField(blank=True, null=True, verbose_name='ارزیابی فرماندار'),
        ),
        migrations.AddField(
            model_name='executive_device',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='وضعیت انتشار'),
        ),
    ]
